- id: '1619286949454'
  alias: Porch Light On
  description: 'On at sunset '
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.porch_light
  mode: single
- id: '1619287062363'
  alias: 'Porch Light Off '
  description: Off at 10pm
  trigger:
  - platform: time
    at: 01:00
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.porch_light
  mode: single
- id: '1619853546057'
  alias: Turn Off Fan
  description: ''
  trigger:
  - platform: time
    at: 08:00
  - platform: numeric_state
    below: '60.0'
    entity_id: sensor.bedroom_temperature
  condition: []
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.bedroom_tower_fan
  mode: single
- id: '1620363654429'
  alias: Group Entry Lights On
  description: ''
  trigger:
  - platform: state
    entity_id: switch.entry_hallway_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.entryway_light
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      area_id: entryway
  - service: switch.turn_on
    target:
      entity_id: switch.kitchen_landing_light
  mode: single
- id: '1620363722406'
  alias: Group Entry Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id: switch.entry_hallway_lights
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: switch.entryway_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      area_id: entryway
  - service: switch.turn_off
    target:
      entity_id: switch.kitchen_landing_light
  mode: single
- id: '1620413283797'
  alias: Group Bedroom Stair/Landing Lights On
  description: Group 3F lights together
  trigger:
  - platform: state
    entity_id: switch.bedroom_stair_light
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: switch.upstairs_hall_light
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.bedroom_stair_light
  - service: switch.turn_on
    target:
      entity_id: switch.upstairs_hall_light
  mode: single
- id: '1620413361238'
  alias: Group Bedroom Stair/Landing Lights Off
  description: Group 3F lights together
  trigger:
  - platform: state
    entity_id: switch.bedroom_stair_light
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: switch.upstairs_hall_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.bedroom_stair_light
  - service: switch.turn_off
    target:
      entity_id: switch.upstairs_hall_light
  mode: single
- id: '1620415247100'
  alias: Away on geofence
  description: ''
  trigger:
  - platform: state
    entity_id: group.everyone
    from: home
    to: not_home
  condition: []
  action:
  - service: script.away
  mode: single
- id: '1620593707549'
  alias: Morning Lights
  description: Turn on the lights downstairs in the morning
  trigger:
  - platform: state
    entity_id: switch.master_bathroom_lights
    from: 'on'
    to: 'off'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '8:45'
    before: '9:30'
  action:
  - service: light.turn_on
    target:
      area_id: kitchen
      entity_id: light.rope_lights
    data:
      brightness: 255
  - service: switch.turn_on
    target:
      entity_id:
      - switch.kitchen_light
      - switch.upstairs_hall_light
      - switch.bedroom_stair_light
  mode: single
- id: '1621360284501'
  alias: Turn on AC
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states.sensor.bedroom_temperature >= states.input_number.ac_high_point
      }}'
  condition:
  - condition: state
    entity_id: binary_sensor.south_bedroom_window
    state: closed
  action:
  - service: climate.turn_on
    target:
      entity_id: climate.air_conditioner
  - service: climate.set_temperature
    data:
      temperature: 62
      hvac_mode: cool
    target:
      entity_id: climate.air_conditioner
  mode: single
- id: '1621361374490'
  alias: Turn off AC
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states.sensor.bedroom_temperature <= states.input_number.ac_low_point
      }}'
  - platform: state
    entity_id: binary_sensor.south_bedroom_window
    from: closed
    to: open
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.air_conditioner
  mode: single
- id: '1630952450601'
  alias: 'Alpha''s Den: Sync Thermostat Display Timeout to DnD On'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.alpha_s_phone_do_not_disturb_sensor
    from: 'off'
    to: priority_only
  condition: []
  action:
  - type: turn_on
    device_id: 0f2ffc993610268f035dc9de2f19eb69
    entity_id: switch.alpha_den_thermostat_display_timer
    domain: switch
  mode: single
- id: '1630952497601'
  alias: 'Alpha''s Den: Sync Thermostat Display Timeout to DnD Off'
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.alpha_s_phone_do_not_disturb_sensor
    to: 'off'
    from: priority_only
  condition: []
  action:
  - type: turn_off
    device_id: 0f2ffc993610268f035dc9de2f19eb69
    entity_id: switch.alpha_den_thermostat_display_timer
    domain: switch
  mode: single
- id: '1631752905743'
  alias: Goat Summit Thermostat Display On With Lights
  description: ''
  trigger:
  - platform: state
    entity_id: light.rope_lights
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.goat_summit_thermostat_display_timer
  mode: single
- id: '1631752934157'
  alias: Goat Summit Thermostat Display Off With Lights
  description: ''
  trigger:
  - platform: state
    entity_id: light.rope_lights
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.goat_summit_thermostat_display_timer
  mode: single
- id: '1632085502491'
  alias: Disable Heat on Window Open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.south_bedroom_window
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.goat_summit_thermostat
    data:
      hvac_mode: 'off'
  mode: single
- id: '1632085538397'
  alias: Enable Heat on Window Close
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.south_bedroom_window
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.goat_summit_thermostat
    data:
      hvac_mode: heat
  mode: single
- id: '1634242989864'
  alias: Morning Heaters
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: script.set_heaters_for_morning
  mode: single
- id: '1634410533194'
  alias: Wolf Dungeon Weekend Heat
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.wolf_dungeon_thermostat
    data:
      temperature: 71
      hvac_mode: heat
  mode: single
- id: '1634410631363'
  alias: Wolf Dungeon Weekend Heat Off
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.wolf_dungeon_thermostat
    data:
      temperature: 65
      hvac_mode: heat
  mode: single
- id: '1638166095726'
  alias: Home Theater Volume Knob Update
  description: ''
  trigger:
  - platform: state
    entity_id: number.home_theater_volume_delta
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state | float != 0.0 }}'
  action:
  - service: number.set_value
    data:
      value: '0'
    target:
      entity_id: number.home_theater_volume_delta
  - service: media_player.volume_set
    data:
      entity_id: media_player.receiver
      volume_level: "{% set target = state_attr('media_player.receiver', 'volume_level')\
        \ + (trigger.to_state.state | float / 100) %} {% if target | float <= 0.0\
        \ %}\n  {{ 0.0 | float }}\n{% elif target | float >= 1.0 %}\n  {{ 1.0 | float\
        \ }}\n{% else %}\n  {{ target | float }}\n{% endif %}\n"
  mode: queued
  max: 10
- id: '1638386608303'
  alias: Turn down Alpha's heat at 3 pm
  description: ''
  trigger:
  - platform: time
    at: '15:00:00'
  condition: []
  action:
  - service: climate.set_temperature
    target:
      device_id: 20f85301d765862ffd80571922d4f2b4
    data:
      temperature: 66
  mode: single
- id: '1638826760916'
  alias: Battery Management - Work Phone Low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.oracle_phone_battery_level
    below: '70'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.work_phone_plug_switch
  mode: single
- id: '1638826856904'
  alias: Battery Management - Work Phone High
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.oracle_phone_battery_level
    above: '80'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.work_phone_plug_switch
  mode: single
- id: '1638829837833'
  alias: Battery Management - Goat Kiosk High
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.goat_summit_kiosk_battery_level
    above: '80'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.goat_summit_tablet_plug_switch
  mode: single
- id: '1638829893467'
  alias: Battery Management - Goat Kiosk Low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.goat_summit_kiosk_battery_level
    below: '70'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.goat_summit_tablet_plug_switch
  mode: single
- id: '1640213597607'
  alias: TV On Dim Thermostat
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
    to: 'on'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.living_room_thermostat_display_timer
  mode: single
- id: '1640213646533'
  alias: TV Off Undim Thermostat
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'on'
    to: 'off'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.living_room_thermostat_display_timer
  mode: single
- id: '1642290377228'
  alias: Garage Door Timer
  description: ''
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_alpha_s_phone
    data:
      message: 'Garage Door has been open for 30 minutes '
  - service: notify.mobile_app_omegaphone
    data:
      message: 'Garage Door has been open for 30 minutes '
  - service: notify.mobile_app_goatphone
    data:
      message: 'Garage Door has been open for 30 minutes '
  mode: single
- id: '1642982933619'
  alias: Landing Lights (Leaving)
  description: ''
  trigger:
  - platform: state
    entity_id: group.entryway
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.landing_lights_down
  mode: single
- id: '1642983026711'
  alias: Landing Lights (Off)
  description: ''
  trigger:
  - platform: state
    entity_id: group.entryway
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.downstairs_lightstrip
  mode: single
- id: '1644096918061'
  alias: Alpha Bathroom Double Taps with Auto Brightness
  description: ''
  use_blueprint:
    path: kpine/ge_double_tap_auto_dimmer.yaml
    input:
      device: d4dae4112b5e0dbbb4936a905352de36
      light: light.alpha_bathroom
      off_brightness: 15
- id: '1644193698096'
  alias: Living Room TV Send WOL Packet
  description: ''
  trigger:
  - platform: device
    device_id: 784adc2f73154cf712cb7c36cc8a8d12
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: b0:37:95:b6:32:a7
  mode: single
- id: '1644195103157'
  alias: Power Off Roku Plug
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.roku_plug
  mode: single
- id: '1644195302261'
  alias: Turn On Roku Plug
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: c5cf1ed03c97583ef5562bf1c208dfd5
    entity_id: remote.roku_ultra
    domain: remote
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.roku_plug
  mode: single
- id: '1644195365273'
  alias: Turn Off Roku Plug
  description: ''
  trigger:
  - platform: device
    device_id: c5cf1ed03c97583ef5562bf1c208dfd5
    domain: media_player
    entity_id: media_player.roku_ultra
    type: turned_off
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.roku_plug
  mode: single
